
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-jekyll:testing"

command:
  build:
  - "jekyll build -s /opt/docs -d /var/www/html"

  update:


  dev:
    - "git submodule update --init --remote"
    - "D:jekyll build -s /opt/docs -d /var/www/html --watch --force_polling"

