title: infracamp.org
description: educational grade development tools
google_analytics:
show_downloads: true
include:

# Make directory-style links
permalink: pretty

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "posts"
  - scope:
      path: "projects/infracamp.wiki"
    values:
      layout: "wiki-default"
  - scope:
      path: "project"
    values:
      layout: "repos-default"
  - scope:
      path: ""
    values:
      layout: "default"
      title: developer camp

sass:
  style: compressed
  sass_dir: _sass

plugins:
- jekyll-optional-front-matter
