title: infracamp.org
description: educational grade development tools
google_analytics:
show_downloads: true
include:


defaults:
  - scope:
      path: "projects/infracamp.wiki"
    values:
      layout: "wiki-default"
  - scope:
      path: ""
    values:
      layout: "default"
      title: developer camp



plugins:
- jekyll-optional-front-matter