name: CI

on:
  push:
  schedule:
    - cron: '25 * * * *'


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: See env
      run: ./pushback.sh
      env:
        SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}