name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: See env
      run: echo wurst > test.txt
    - name: See env
      run: git add .
    - name: See env
      run: git config --global user.email "you@example.com"
    - name: See env
      run: git config --global user.name "Your Name"

    - name: See env
      run: git commit -m "autoload"
    - name: See env
      run: git push origin HEAD:master
